### ISSUE TITLE
'render': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by jyaworski** [puppet-community/modulesync#64]
Hello:

I went to update puppet-network to use modulesync. I did a fresh install of modulesync with multiple ruby versions, and they all return this:

````
joseph.yaworski@jyaworski-mbpr ~/github/modulesync_config (git)-[manage_network] % rvm 2.2.3 do msync update    
Syncing puppet-network
Cloning repository fresh
Cloning from git@github.com:jyaworski/puppet-network.git
Creating new branch modulesync
No config file under ./modules/puppet-network/.sync.yml found, using default values
(ERB):8:in `render': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/joseph.yaworski/.rvm/gems/ruby-2.2.3/gems/modulesync-0.6.1/lib/modulesync/renderer.rb:27:in `render'
	from /Users/joseph.yaworski/.rvm/gems/ruby-2.2.3/gems/modulesync-0.6.1/lib/modulesync.rb:78:in `block (2 levels) in run'
	from /Users/joseph.yaworski/.rvm/gems/ruby-2.2.3/gems/modulesync-0.6.1/lib/modulesync.rb:68:in `each'
	from /Users/joseph.yaworski/.rvm/gems/ruby-2.2.3/gems/modulesync-0.6.1/lib/modulesync.rb:68:in `block in run'
	from /Users/joseph.yaworski/.rvm/gems/ruby-2.2.3/gems/modulesync-0.6.1/lib/modulesync.rb:57:in `each'
	from /Users/joseph.yaworski/.rvm/gems/ruby-2.2.3/gems/modulesync-0.6.1/lib/modulesync.rb:57:in `run'
	from /Users/joseph.yaworski/.rvm/gems/ruby-2.2.3/gems/modulesync-0.6.1/bin/msync:8:in `<top (required)>'
	from /Users/joseph.yaworski/.rvm/gems/ruby-2.2.3/bin/msync:23:in `load'
	from /Users/joseph.yaworski/.rvm/gems/ruby-2.2.3/bin/msync:23:in `<main>'
	from /Users/joseph.yaworski/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/joseph.yaworski/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
````

I'm on OSX. Any ideas?

**Comment by igalic** [comment]
any chance it's choking on this bit here from [moduleroot/.rubocop.yml](https://github.com/puppet-community/modulesync_config/blob/master/moduleroot/.rubocop.yml#L8-L10)
```erb
    <%- @configs['AllCops']['Exclude'].each do |x| -%>
    - <%= x %>
    <%- end -%>
```
